Differences in src/lpc176x/Makefile:

- Lines with differences: 2 lines in 1 blocks

Detailed Differences:

--- /media/mks/5dcae443-0796-4029-ae6c-bf5bd2a37067/home/mks/klipper/src/lpc176x/Makefile	2023-10-20 03:52:19.620163937 -0400
+++ /home/mks/firmware_comparison/downloads/klipper/src/lpc176x/Makefile	2024-10-08 17:45:26.888217467 -0400
@@ -7,7 +7,7 @@
 
 CFLAGS += -mthumb -mcpu=cortex-m3 -Ilib/lpc176x/device -Ilib/cmsis-core
 
-CFLAGS_klipper.elf += --specs=nano.specs --specs=nosys.specs
+CFLAGS_klipper.elf += -nostdlib -lgcc -lc_nano
 CFLAGS_klipper.elf += -T $(OUT)src/generic/armcm_link.ld
 $(OUT)klipper.elf: $(OUT)src/generic/armcm_link.ld
 
