Differences in src/rp2040/Makefile:

- Lines with differences: 4 lines in 2 blocks

Detailed Differences:

--- /media/mks/5dcae443-0796-4029-ae6c-bf5bd2a37067/home/mks/CanBoot/src/rp2040/Makefile	2023-08-12 06:18:51.920709110 -0400
+++ /home/mks/firmware_comparison/downloads/CanBoot/src/rp2040/Makefile	2024-10-08 17:45:28.589223696 -0400
@@ -8,7 +8,7 @@
 CFLAGS += -mcpu=cortex-m0plus -mthumb -Ilib/cmsis-core
 CFLAGS += -Ilib/rp2040 -Ilib/rp2040/cmsis_include -Ilib/fast-hash -Ilib/can2040 -Ilib/rp2040/pico/flash/ -Ilib/rp2040/pico/bootrom/
 
-CFLAGS_katapult.elf += --specs=nano.specs --specs=nosys.specs
+CFLAGS_katapult.elf += -nostdlib -lgcc -lc_nano
 CFLAGS_katapult.elf += -T $(OUT)src/rp2040/rp2040_link.ld
 
 # Add source files
@@ -62,6 +62,6 @@
 
 # Deployer build
 deployer-y += generic/armcm_boot.c generic/armcm_reset.c $(mcu-y)
-CFLAGS_deployer.elf += --specs=nano.specs --specs=nosys.specs
+CFLAGS_deployer.elf += -nostdlib -lgcc -lc_nano
 CFLAGS_deployer.elf += -T $(OUT)src/generic/armcm_deployer.ld
 $(OUT)deployer.elf: $(OUT)src/generic/armcm_deployer.ld
