Differences in src/hc32f460/Makefile:

- Lines with differences: 2 lines in 1 blocks

Detailed Differences:

--- /media/mks/5dcae443-0796-4029-ae6c-bf5bd2a37067/home/mks/klipper/src/hc32f460/Makefile	2023-10-20 03:52:19.608163937 -0400
+++ /home/mks/firmware_comparison/downloads/klipper/src/hc32f460/Makefile	2024-10-08 17:45:26.888217467 -0400
@@ -7,7 +7,7 @@
 
 CFLAGS += -mthumb -mcpu=cortex-m4 -Isrc/hc32f460 -Ilib/hc32f460/driver/inc -Ilib/hc32f460/mcu/common -Ilib/cmsis-core -DHC32F460
 
-CFLAGS_klipper.elf += --specs=nano.specs --specs=nosys.specs
+CFLAGS_klipper.elf += -nostdlib -lgcc -lc_nano
 CFLAGS_klipper.elf += -T $(OUT)src/generic/armcm_link.ld
 $(OUT)klipper.elf: $(OUT)src/generic/armcm_link.ld
 
