Differences in Makefile:

- Lines with differences: 4 lines in 1 blocks

Detailed Differences:

--- /media/mks/5dcae443-0796-4029-ae6c-bf5bd2a37067/home/mks/CanBoot/Makefile	2023-08-12 06:18:50.848709110 -0400
+++ /home/mks/firmware_comparison/downloads/CanBoot/Makefile	2024-10-08 17:45:28.434223129 -0400
@@ -30,10 +30,10 @@
 cc-option=$(shell if test -z "`$(1) $(2) -S -o /dev/null -xc /dev/null 2>&1`" \
     ; then echo "$(2)"; else echo "$(3)"; fi ;)
 
-CFLAGS := -I$(OUT) -Isrc -I$(OUT)board-generic/ -std=gnu11 -Os -MD \
+CFLAGS := -iquote $(OUT) -iquote src -iquote $(OUT)board-generic/ -std=gnu11 -Os -MD \
     -Wall -Wold-style-definition $(call cc-option,$(CC),-Wtype-limits,) \
     -ffunction-sections -fdata-sections -fno-delete-null-pointer-checks
-CFLAGS += -flto -fwhole-program -fno-use-linker-plugin -ggdb3
+CFLAGS += -flto=auto -fwhole-program -fno-use-linker-plugin -ggdb3
 
 OBJS_katapult.elf = $(patsubst %.c, $(OUT)src/%.o,$(src-y))
 OBJS_katapult.elf += $(OUT)compile_time_request.o
