Differences in Makefile:

- Lines with differences: 62 lines in 1 blocks

Detailed Differences:

--- /media/mks/5dcae443-0796-4029-ae6c-bf5bd2a37067/home/mks/crowsnest/Makefile	2023-12-15 01:50:44.402398135 -0500
+++ /home/mks/firmware_comparison/downloads/crowsnest/Makefile	2024-10-08 17:45:29.818228183 -0400
@@ -1,60 +1,53 @@
-#### webcamd - A webcam Service for multiple Cams and Stream Services.
+#### crowsnest - A webcam Service for multiple Cams and Stream Services.
 ####
 #### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
-#### Copyright 2021 - 2022
+#### Copyright 2021 - 2023
+#### Co-authored by Patrick Gehrsitz aka mryel00 <mryel00.github@gmail.com>
+#### Copyright 2023 - till today
 #### https://github.com/mainsail-crew/crowsnest
 ####
 #### This File is distributed under GPLv3
 ####
 
-.PHONY: build buildclean config help install unsinstall
+#### Self-Documenting Makefile
+#### This is based on https://gellardo.github.io/blog/posts/2021-06-10-self-documenting-makefile/
 
-# Setup
-USER = $(shell whoami)
-BIN_FOLDER = bin
-
-all: help
-
-help:
-	@echo "This is intended to install crowsnest."
-	@echo ""
-	@echo "Some Parts need 'sudo' privileges."
-	@echo "You'll be asked for password, if needed."
-	@echo ""
-	@echo " Usage: make [action]"
-	@echo ""
-	@echo "  Available actions:"
-	@echo ""
-	@echo "   config       Configures Installer"
-	@echo "   install      Installs crowsnest (needs sudo)"
-	@echo "   uninstall    Uninstalls crowsnest (needs sudo)"
-	@echo "   build        builds binaries"
-	@echo "   buildclean   cleans binaries (for recompile)"
-	@echo "   clean        Removes Installer config"
-	@echo ""
+.DEFAULT_GOAL := help
+.PHONY: help
 
-install:
+install: ## Install crowsnest (needs leading sudo)
 	@bash -c 'tools/install.sh'
 
-uninstall:
+uninstall: ## Uninstall crowsnest
 	@bash -c 'tools/uninstall.sh'
 
-build:
-	$(MAKE) -C $(BIN_FOLDER)
+build: ## Compile backends / streamer
+	bash -c 'bin/build.sh --build'
 
-buildclean:
-	$(MAKE) -C $(BIN_FOLDER) clean
+buildclean: ## Clean backends / streamer (for rebuilding)
+	bash -c 'bin/build.sh --clean'
 
-clean:
+clean: ## Clean .config
 	@if [ -f tools/.config ]; then rm -f tools/.config; fi
-	@echo "Removed installer config file ..."
+	@printf "Removed installer config file ...\n"
 
-config:
+config: ## Configure crowsnest installer
 	@bash -c 'tools/configure.sh'
 
-report:
+help: ## Shows this help
+	@printf "crowsnest - A webcam Service for multiple Cams and Stream Services.\n"
+	@printf "Usage:\n\n"
+	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'
+
+update: ## Update crowsnest (fetches and pulls repository changes)
+	@git fetch && git pull
+	@bash -c 'bin/build.sh --reclone'
+	${MAKE} build
+
+report: ## Generate report.txt
 	@if [ -f ~/report.txt ]; then rm -f ~/report.txt; fi
 	@bash -c 'tools/dev-helper.sh -a >> ~/report.txt'
 	@sed -ri 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' ~/report.txt
 
-
+fixworkingdirectory: ## Fix service file WorkingDirectory path
+	@sudo sed -i "s~\(WorkingDirectory=\).*~\1$$PWD~" /etc/systemd/system/crowsnest.service
