Differences in src/lpc176x/Makefile:

- Lines with differences: 4 lines in 2 blocks

Detailed Differences:

--- /media/mks/5dcae443-0796-4029-ae6c-bf5bd2a37067/home/mks/CanBoot/src/lpc176x/Makefile	2023-08-12 06:18:51.916709110 -0400
+++ /home/mks/firmware_comparison/downloads/CanBoot/src/lpc176x/Makefile	2024-10-08 17:45:28.589223696 -0400
@@ -8,7 +8,7 @@
 CFLAGS += -mthumb -mcpu=cortex-m3 -Ilib/lpc176x/device -Ilib/cmsis-core
 CFLAGS += -Wno-nonnull
 
-CFLAGS_katapult.elf += --specs=nano.specs --specs=nosys.specs
+CFLAGS_katapult.elf += -nostdlib -lgcc -lc_nano
 CFLAGS_katapult.elf += -T $(OUT)src/generic/armcm_link.ld
 $(OUT)katapult.elf: $(OUT)src/generic/armcm_link.ld
 
@@ -26,6 +26,6 @@
 
 # Deployer build
 deployer-y += generic/armcm_boot.c generic/armcm_reset.c $(mcu-y)
-CFLAGS_deployer.elf += --specs=nano.specs --specs=nosys.specs
+CFLAGS_deployer.elf += -nostdlib -lgcc -lc_nano
 CFLAGS_deployer.elf += -T $(OUT)src/generic/armcm_deployer.ld
 $(OUT)deployer.elf: $(OUT)src/generic/armcm_deployer.ld
